CREATE TABLE IF NOT EXISTS dealers (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  company TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS dealer_logins (
  id SERIAL PRIMARY KEY,
  login TEXT NOT NULL UNIQUE,
  dealer_id INTEGER NOT NULL REFERENCES dealers(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
