CREATE TABLE IF NOT EXISTS dealers (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  company TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS base_rate NUMERIC(8,4) NOT NULL DEFAULT 0.45;
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS quarter_rate_1 NUMERIC(8,4) NOT NULL DEFAULT 0.60;
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS quarter_rate_2 NUMERIC(8,4) NOT NULL DEFAULT 0.65;
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS quarter_rate_3 NUMERIC(8,4) NOT NULL DEFAULT 0.70;
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS actual_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE dealers ADD COLUMN IF NOT EXISTS plan_count INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS dealer_logins (
  id SERIAL PRIMARY KEY,
  login TEXT NOT NULL UNIQUE,
  dealer_id INTEGER NOT NULL REFERENCES dealers(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE dealer_logins ADD COLUMN IF NOT EXISTS base_rate NUMERIC(8,4) NOT NULL DEFAULT 0.45;
ALTER TABLE dealer_logins ADD COLUMN IF NOT EXISTS quarter_rate_1 NUMERIC(8,4) NOT NULL DEFAULT 0.60;
ALTER TABLE dealer_logins ADD COLUMN IF NOT EXISTS quarter_rate_2 NUMERIC(8,4) NOT NULL DEFAULT 0.65;
ALTER TABLE dealer_logins ADD COLUMN IF NOT EXISTS quarter_rate_3 NUMERIC(8,4) NOT NULL DEFAULT 0.70;
ALTER TABLE dealer_logins ADD COLUMN IF NOT EXISTS plan_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE dealer_logins ADD COLUMN IF NOT EXISTS actual_count INTEGER NOT NULL DEFAULT 0;
